spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  web:
    resources:
      cache:
        period: 86400

server:
  port: 8080

logging:
  level:
    root: WARN
    com.aigenxlab.loginapp: INFO
  pattern:
    console: '{"time":"%d","level":"%p","msg":"%m","logger":"%logger"}%n'

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
